# Generated by Django 5.2 on 2025-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationbot',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
