# Generated by Django 5.2 on 2025-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_administrationbot_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='access_bots',
            field=models.ManyToManyField(blank=True, to='admin_app.administrationbot'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
